### PR TITLE
lots of fixes and tweaks done for freeaoe

### PR DESCRIPTION
**Pull request by sandsmark**
not sure if everything is interesting, I'll also open a PR for AGE so it works with this.

### CODE REVIEW

**Comment by Tapsa** [comment]
I like that you made a replacement for boost, but is zlib still useful?

**Comment by sandsmark** [comment]
yeah, but I planned on adding miniz as a fallback if it isn't available when building (for example on Windows)

**Comment by sandsmark** [comment]
added miniz, should be used automatically when zlib isn't available.

**Comment by Tapsa** [comment]
Thanks for the ideas mate.

**Comment by sandsmark** [comment]
fwiw, I saw you have implemented SMP support (I merged in your latest stuff into my branch), if you want SMX support here's my implementation; https://github.com/sandsmark/genieutils/blob/master/src/resource/SmxFrame.cpp (and smxfile.cpp)

**Pull request closed without merging**
